### ISSUE TITLE
Question about the classification

### ISSUE THREAD

**Issue by botianzhe** [DaddyJin/awesome-faceReenactment#13]
What is the difference between the Talking Face Generation and Face Reenactment？

**Comment by DaddyJin** [comment]
Originally, Face Reenactment refers to **video-driven** animation method while Talking Face Generation denotes **audio-driven** methods. Recently, some video-driven methods[1-2] turn to use Talking Face Generation as their task definition, causing the confusion of concepts.

[1] Depth-Aware Generative Adversarial Network for Talking Head Video Generation
[2] MetaPortrait: Identity-Preserving Talking Head Generation with Fast Personalized Adaptation

**Comment by botianzhe** [comment]
> Thanks for your reply. This answer solves my confusion.
